sudo: required
services:
  - docker

before_install:
  - docker build -t aidandang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aidandang/react-test npm run test

after_success:
  - docker build -t aidandang/multi-client ./client
  - docker build -t aidandang/multi-nginx ./nginx
  - docker build -t aidandang/multi-server ./server
  - docker build -t aidandang/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aidandang/multi-client
  - docker push aidandang/multi-nginx
  - docker push aidandang/multi-server
  - docker push aidandang/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-221926906753'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
